# Write lib/utils/app_version_generated.dart with current Ver.YYYY.MM.XYZ.ENV from generate_version.py.
# Run from khono_recruite/ (e.g. by flutter_run_with_version.ps1 or manually).

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$khonoRoot = Split-Path -Parent $scriptDir
Set-Location $khonoRoot

$version = & python "scripts\generate_version.py" 2>$null
if (-not $version) { $version = "Ver.0.0.0.LOCAL" }

$content = @"
/// Generated by scripts/update_version_file - do not edit by hand.
/// Run scripts/update_version_file.ps1 (or run.ps1) to refresh.
const String kGeneratedAppVersion = '$version';
"@

$outPath = "lib\utils\app_version_generated.dart"
$content | Set-Content -Path $outPath -Encoding UTF8
Write-Host "Updated $outPath with $version"
