#!/usr/bin/env bash
# Write lib/utils/app_version_generated.dart with current Ver.YYYY.MM.XYZ.ENV.
# Run from khono_recruite/ (e.g. by flutter_run_with_version.sh or manually).

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
KHONO_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$KHONO_ROOT"

VERSION="$(python3 scripts/generate_version.py 2>/dev/null || python scripts/generate_version.py 2>/dev/null || echo 'Ver.0.0.0.LOCAL')"
OUT_PATH="lib/utils/app_version_generated.dart"
cat > "$OUT_PATH" << EOF
/// Generated by scripts/update_version_file - do not edit by hand.
/// Run scripts/update_version_file.ps1 (or run.ps1) to refresh.
const String kGeneratedAppVersion = '$VERSION';
EOF
echo "Updated $OUT_PATH with $VERSION"
