"""add_external_analysis_id_to_cv_analyses

Revision ID: 20240314_add_external_analysis_id
Revises: 
Create Date: 2024-03-14 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20240314_add_external_analysis_id'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_analyses', sa.Column('external_analysis_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_cv_analyses_external_analysis_id'), 'cv_analyses', ['external_analysis_id'], unique=False)
    op.create_index(op.f('ix_cv_analyses_status'), 'cv_analyses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_analyses_status'), table_name='cv_analyses')
    op.drop_index(op.f('ix_cv_analyses_external_analysis_id'), table_name='cv_analyses')
    op.drop_column('cv_analyses', 'external_analysis_id')
    # ### end Alembic commands ###
