"""add_analyser_sync_columns_to_candidates_fixed

Revision ID: 20260328_add_analyser_sync_columns_fixed
Revises: 7ec5a07c5b21
Create Date: 2024-03-28 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = '20260328_add_analyser_sync_columns_fixed'
down_revision = '7ec5a07c5b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add analyser_id for direct reference to external CV Analyser
    op.add_column('candidates', sa.Column('analyser_id', sa.String(length=255), nullable=True))
    op.create_index('ix_candidates_analyser_id', 'candidates', ['analyser_id'], unique=False)
    
    # Add cv_analysis_status for status tracking (pending/processing/completed/failed)
    op.add_column('candidates', sa.Column('cv_analysis_status', sa.String(length=20), nullable=True))
    op.create_index('ix_candidates_cv_analysis_status', 'candidates', ['cv_analysis_status'], unique=False)
    
    # Add cv_analysis_promoted_at timestamp
    op.add_column('candidates', sa.Column('cv_analysis_promoted_at', sa.DateTime(), nullable=True))
    
    # Add last_cv_analysis_id as integer (no foreign key constraint due to cross-database)
    op.add_column('candidates', sa.Column('last_cv_analysis_id', sa.Integer(), nullable=True))
    op.create_index('ix_candidates_last_cv_analysis_id', 'candidates', ['last_cv_analysis_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes first
    op.drop_index('ix_candidates_last_cv_analysis_id', table_name='candidates')
    op.drop_index('ix_candidates_cv_analysis_status', table_name='candidates')
    op.drop_index('ix_candidates_analyser_id', table_name='candidates')
    
    # Drop columns
    op.drop_column('candidates', 'last_cv_analysis_id')
    op.drop_column('candidates', 'cv_analysis_promoted_at')
    op.drop_column('candidates', 'cv_analysis_status')
    op.drop_column('candidates', 'analyser_id')
    
    # ### end Alembic commands ###
