"""add_analyser_sync_columns_to_candidates

Revision ID: 20260328_add_analyser_sync_columns
Revises: 7ec5a07c5b21
Create Date: 2024-03-28 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '20260328_add_analyser_sync_columns'
down_revision = '7ec5a07c5b21'
branch_labels = None
depends_on = None


def _has_column(table_name, column_name):
    bind = op.get_bind()
    insp = inspect(bind)
    cols = [c["name"] for c in insp.get_columns(table_name)]
    return column_name in cols


def _has_index(table_name, index_name):
    bind = op.get_bind()
    insp = inspect(bind)
    idx = [i["name"] for i in insp.get_indexes(table_name)]
    return index_name in idx


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add analyser_id for direct reference to external CV Analyser
    if not _has_column('candidates', 'analyser_id'):
        op.add_column('candidates', sa.Column('analyser_id', sa.String(length=255), nullable=True))
    
    if not _has_index('candidates', 'ix_candidates_analyser_id'):
        op.create_index('ix_candidates_analyser_id', 'candidates', ['analyser_id'], unique=False)
    
    # Add cv_analysis_status for status tracking (pending/processing/completed/failed)
    if not _has_column('candidates', 'cv_analysis_status'):
        op.add_column('candidates', sa.Column('cv_analysis_status', sa.String(length=20), nullable=True))
    
    if not _has_index('candidates', 'ix_candidates_cv_analysis_status'):
        op.create_index('ix_candidates_cv_analysis_status', 'candidates', ['cv_analysis_status'], unique=False)
    
    # Add cv_analysis_promoted_at timestamp
    if not _has_column('candidates', 'cv_analysis_promoted_at'):
        op.add_column('candidates', sa.Column('cv_analysis_promoted_at', sa.DateTime(), nullable=True))
    
    # Add last_cv_analysis_id foreign key to link to local CVAnalysis
    if not _has_column('candidates', 'last_cv_analysis_id'):
        op.add_column('candidates', sa.Column('last_cv_analysis_id', sa.Integer(), nullable=True))
    
    # Add foreign key only if last_cv_analysis_id exists and FK doesn't
    bind = op.get_bind()
    insp = inspect(bind)
    fks = [fk['name'] for fk in insp.get_foreign_keys('candidates')]
    if 'fk_candidates_last_cv_analysis' not in fks:
        op.create_foreign_key(
            'fk_candidates_last_cv_analysis',
            'candidates',
            'cv_analyses',
            ['last_cv_analysis_id'],
            ['id'],
            referent_schema='cv_analyser'
        )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key first
    bind = op.get_bind()
    insp = inspect(bind)
    fks = [fk['name'] for fk in insp.get_foreign_keys('candidates')]
    if 'fk_candidates_last_cv_analysis' in fks:
        op.drop_constraint('fk_candidates_last_cv_analysis', 'candidates', type_='foreignkey')
    
    # Drop columns
    if _has_column('candidates', 'last_cv_analysis_id'):
        op.drop_column('candidates', 'last_cv_analysis_id')
    if _has_column('candidates', 'cv_analysis_promoted_at'):
        op.drop_column('candidates', 'cv_analysis_promoted_at')
    
    if _has_index('candidates', 'ix_candidates_cv_analysis_status'):
        op.drop_index('ix_candidates_cv_analysis_status', table_name='candidates')
    if _has_column('candidates', 'cv_analysis_status'):
        op.drop_column('candidates', 'cv_analysis_status')
    
    if _has_index('candidates', 'ix_candidates_analyser_id'):
        op.drop_index('ix_candidates_analyser_id', table_name='candidates')
    if _has_column('candidates', 'analyser_id'):
        op.drop_column('candidates', 'analyser_id')
    
    # ### end Alembic commands ###
