"""Add missing application scoring columns

Revision ID: 33f86c05b761
Revises: d544fdd839da
Create Date: 2026-02-11 13:04:57.860691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33f86c05b761'
down_revision = 'd544fdd839da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scoring_breakdown', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('knockout_rule_violations', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('finished_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        batch_op.drop_column('finished_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('knockout_rule_violations')
        batch_op.drop_column('scoring_breakdown')

    # ### end Alembic commands ###
