"""Add missing application scoring columns

Revision ID: 33f86c05b761
Revises: 8c2b6b1a9d21
Create Date: 2026-02-11 13:04:57.860691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '33f86c05b761'
down_revision = '8c2b6b1a9d21'
branch_labels = None
depends_on = None


def _has_column(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = inspect(bind)
    cols = inspector.get_columns(table_name)
    return any(c.get('name') == column_name for c in cols)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        if not _has_column('applications', 'scoring_breakdown'):
            batch_op.add_column(sa.Column('scoring_breakdown', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        if not _has_column('applications', 'knockout_rule_violations'):
            batch_op.add_column(sa.Column('knockout_rule_violations', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        if not _has_column('cv_analyses', 'status'):
            batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        if not _has_column('cv_analyses', 'started_at'):
            batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        if not _has_column('cv_analyses', 'finished_at'):
            batch_op.add_column(sa.Column('finished_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        if _has_column('cv_analyses', 'finished_at'):
            batch_op.drop_column('finished_at')
        if _has_column('cv_analyses', 'started_at'):
            batch_op.drop_column('started_at')
        if _has_column('cv_analyses', 'status'):
            batch_op.drop_column('status')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        if _has_column('applications', 'knockout_rule_violations'):
            batch_op.drop_column('knockout_rule_violations')
        if _has_column('applications', 'scoring_breakdown'):
            batch_op.drop_column('scoring_breakdown')

    # ### end Alembic commands ###
