"""init schema

Revision ID: d544fdd839da
Revises: 
Create Date: 2026-02-09 09:29:46.441331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd544fdd839da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('profile', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('enrollment_completed', sa.Boolean(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('first_login', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=32), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_verified', sa.Boolean(), nullable=True),
    sa.Column('mfa_backup_codes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('id_number', sa.String(length=100), nullable=True),
    sa.Column('linkedin', sa.String(length=250), nullable=True),
    sa.Column('github', sa.String(length=250), nullable=True),
    sa.Column('cv_url', sa.String(length=500), nullable=True),
    sa.Column('cv_text', sa.Text(), nullable=True),
    sa.Column('portfolio', sa.String(length=500), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=1024), nullable=True),
    sa.Column('education', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('skills', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('work_experience', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('certifications', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('languages', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('documents', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('profile', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('overall_interview_score', sa.Float(), nullable=True),
    sa.Column('cv_score', sa.Integer(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('notifications_email', sa.Boolean(), nullable=True),
    sa.Column('notifications_push', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('assistant_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('meeting_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_table('requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('salary_period', sa.String(length=20), nullable=True),
    sa.Column('job_summary', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.String(length=80), nullable=True),
    sa.Column('responsibilities', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('company_details', sa.Text(), nullable=True),
    sa.Column('qualifications', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('required_skills', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('min_experience', sa.Float(), nullable=True),
    sa.Column('knockout_rules', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('weightings', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('assessment_pack', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('published_on', sa.DateTime(), nullable=True),
    sa.Column('vacancy', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('banner', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_presence',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_typing', sa.Boolean(), nullable=True),
    sa.Column('typing_in_thread', sa.Integer(), nullable=True),
    sa.Column('socket_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('requisition_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('draft_data', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('cv_score', sa.Float(), nullable=True),
    sa.Column('cv_parser_result', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('assessment_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('scoring_breakdown', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('knockout_rule_violations', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('assessed_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_saved_screen', sa.String(length=50), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.Column('last_interview_date', sa.DateTime(), nullable=True),
    sa.Column('interview_status', sa.String(length=50), nullable=True),
    sa.Column('interview_feedback_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('message_metadata', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_participants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_thread_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_thread_id'], ['chat_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_thread_id')
    )
    with op.batch_alter_table('chat_participants', schema=None) as batch_op:
        batch_op.create_index('idx_chat_thread', ['chat_thread_id'], unique=False)
        batch_op.create_index('idx_chat_user', ['user_id'], unique=False)

    op.create_table('cv_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('cv_text', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_activity_logs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_activity_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('assessment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('scores', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('percentage_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('hiring_manager_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('interview_type', sa.String(length=50), nullable=True),
    sa.Column('meeting_link', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('google_calendar_event_link', sa.String(length=500), nullable=True),
    sa.Column('google_calendar_hangout_link', sa.String(length=500), nullable=True),
    sa.Column('last_calendar_sync', sa.DateTime(), nullable=True),
    sa.Column('feedback_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('no_show_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['hiring_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_google_calendar_event_id'), ['google_calendar_event_id'], unique=False)

    op.create_table('message_read_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_user')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('drafted_by', sa.Integer(), nullable=False),
    sa.Column('hiring_manager_id', sa.Integer(), nullable=True),
    sa.Column('hr_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('signed_by', sa.Integer(), nullable=True),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('allowances', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('bonuses', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('work_location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'APPROVED', 'SENT', 'SIGNED', 'REJECTED', 'EXPIRED', 'WITHDRAWN', name='offer_status'), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_public_id', sa.String(length=255), nullable=True),
    sa.Column('pdf_generated_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('candidate_ip', sa.String(length=45), nullable=True),
    sa.Column('candidate_user_agent', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('offer_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['drafted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hiring_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hr_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', name='uq_offer_application')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_status'), ['status'], unique=False)

    op.create_table('interview_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_name', sa.String(length=200), nullable=True),
    sa.Column('interviewer_email', sa.String(length=200), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('technical_skills', sa.Integer(), nullable=True),
    sa.Column('communication', sa.Integer(), nullable=True),
    sa.Column('culture_fit', sa.Integer(), nullable=True),
    sa.Column('problem_solving', sa.Integer(), nullable=True),
    sa.Column('experience_relevance', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('private_notes', sa.Text(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'interviewer_id', name='unique_interviewer_feedback')
    )
    op.create_table('interview_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'reminder_type', name='unique_reminder_type')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('interview_reminders')
    op.drop_table('interview_notes')
    op.drop_table('interview_feedback')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_status'))
        batch_op.drop_index(batch_op.f('ix_offers_application_id'))

    op.drop_table('offers')
    op.drop_table('message_read_status')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_google_calendar_event_id'))

    op.drop_table('interviews')
    op.drop_table('assessment_results')
    with op.batch_alter_table('job_activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_activity_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_job_activity_logs_job_id'))

    op.drop_table('job_activity_logs')
    op.drop_table('cv_analyses')
    with op.batch_alter_table('chat_participants', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_user')
        batch_op.drop_index('idx_chat_thread')

    op.drop_table('chat_participants')
    op.drop_table('chat_messages')
    op.drop_table('applications')
    op.drop_table('user_presence')
    op.drop_table('shared_notes')
    op.drop_table('requisitions')
    op.drop_table('oauth_connections')
    op.drop_table('meetings')
    op.drop_table('conversations')
    op.drop_table('chat_threads')
    op.drop_table('candidates')
    op.drop_table('audit_logs')
    op.drop_table('verification_codes')
    op.drop_table('users')
    # ### end Alembic commands ###
