"""Add education_field to candidates

Revision ID: e8ccb76d890a
Revises: e3c584269e39
Create Date: 2026-04-14 07:11:31.051173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8ccb76d890a'
down_revision = 'e3c584269e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education_field', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('education_field')
    # ### end Alembic commands ###

    # ### end Alembic commands ###
